const input = document.getElementById("input");
const output = document.getElementById("output");

const words = new Map([
    ["a", "[emphasis]"],
    ["akesi", "lizard, reptile, none-cute animal"],
    ["ala", "no, not, none, un-, nothing, negation, zero"],
    ["alasa", "gather, hunt, forage, search, try"],
    ["ale", "everything, anything, life, universe, every, all, complete, whole"],
    ["ali", "everything, anything, life, universe, every, all, conplete, whole"],
    ["anpa", "bottom, lower part, under, below, floor, lower, bottom, humble"],
    ["ante", "difference, different, change, alter, otherwise, else"],
    ["anu", "or"],
    ["awen", "wait, keep, remain, stationary, permanent, continue"],
    ["e", "[object follows]"],
    ["en", "and"],
    ["esun", "market, shop, business, trade, sell, buy"],
    ["ijo", "thing, something, stuff, anything, object"],
    ["ike", "bad, negative, evil, uneccessary"],
    ["ilo", "tool, device, machine, computer"],
    ["insa", "inner, center, stomach, internal"],
    ["jaki", "dirty, gross, filthy, toxic"],
    ["jan", "person, people, human, sombody, anybody"],
    ["jelo", "yellow"],
    ["jo", "have, contain, recieve, get, take, obtain"],
    ["kala", "fish, sea creature"],
    ["kalama", "sound, noise, voice, ring, play (instrument)"],
    ["kama", "come, become, arrive, happen, future, summon"],
    ["kasi", "plant, leaf, herb, tree, wood"],
    ["ken", "is able to, exists, allowed, may, possible, enable"],
    ["kepeken", "use, with"],
    ["kili", "fruit, vegetable, mushroom"],
    ["kin", "also, too, even, indeed (emphasize words before it)"],
    ["kipisi", "part, partition, split, cut, divide"],
    ["kiwen", "hard, solid, stone-like, rock, mineral"],
    ["ko", "semi-solid, squishy, substance, powder, gum"],
    ["kon", "air, wind, smell, soul, gaseous"],
    ["kule", "color, paint, colorful, paint"],
    ["kulupu", "group, community, society, company, people"],
    ["kute", "listen, hear"],
    ["la", "[between adverb or phrase of context and rest of sentence"],
    ["lape", "sleep, rest"],
    ["laso", "blue, green"],
    ["lawa", "head, mind, lead, in charge, control"],
    ["len", "clothing, fabric"],
    ["lete", "cold, uncooked, chill"],
    ["li", "[between subject and verb]"],
    ["lili", "small, little, young, few, less"],
    ["linja", "long, thin, floppy, string, rope, hair, thread"],
    ["lipu", "flat, bendable, paper, card, ticket, document"],
    ["loje", "red"],
    ["lon", "in, at, on, present, real, true, exist"],
    ["luka", "hand, arm"],
    ["lukin", "see, look, watch, read, pay attention"],
    ["lupa", "hole, window, door"],
    ["ma", "land, earth, country, outdoor area"],
    ["mama", "parent, guardian, mother, father"],
    ["mani", "money, material wealth, currency, dollar"],
    ["meli", "woman, female, wife, girlfriend, feminine"],
    ["mi", "I, we, my, our"],
    ["mije", "man, boy, male, husband, boyfriend"],
    ["moku", "food, meal, eat, drink, consume, ingest"],
    ["moli", "deadly, death, lethal, dangerous"],
    ["back, rear end, butt, behind"],
    ["mu", "[any animal sound]"],
    ["mun", "moon, lunar"],
    ["musi", "fun, playing, game, art, entertainment, amusement"],
    ["mute", "many, very much, several, a lot, abundant, numerous, more"],
    ["namako", "additive, accessory, something extra"],
    ["nanpa", "number"],
    ["nasin", "way, custom, road, path, system, method, religion"],
    ["nena", "bump, nose, hi, mountain, button"],
    ["ni", "this/that"],
    ["nimi", "word, name"],
    ["noka", "leg, foot"],
    ["o", "[used after addressing someone, command]"],
    ["oko", "eye"],
    ["olin", "love, lust"],
    ["ona", "[third person, gender neutral pronoun]"],
    ["open", "open, turn on"],
    ["pakala", "blunder, accident, mistake, distruction, damage, break, [can be swear word]"],
    ["pali", "activity, work, project, word, function, act, make, build, create"],
    ["palisa", "long, mostly hard object: rod, stick, branch"],
    ["pan", "grain, cereal, rice"],
    ["pana", "give, put, place, release, send, emit, cause, transfer"],
    ["pi", "[of, belonging to]"],
    ["pilin", "feeling, emotion, hard, sense, touch"],
    ["pimeja", "black, dark"],
    ["pini", "end, tip, finish, complete, done, age"],
    ["pipi", "bug, insect, spider"],
    ["poka", "side, hip, next to"],
    ["pona", "good, simple, positivity, great, ok, thanks"],
    ["pu", "the official toki pona book"],
    ["sama", "same, similar, equal"],
    ["seli", "warm, fire, heat"],
    ["selo", "outisde, surface, skin, shell, peel"],
    ["seme", "what, which, wh- (question word)"],
    ["sewi", "high, up, above, top, over, on"],
    ["sijelo", "body, physical state"],
    ["sike", "wheel, sphere, ball, cycle"],
    ["sin", "new, fresh, another, more, renew"],
    ["sina", "you, your"],
    ["sinpin", "front, chest, torso, face, wall"],
    ["sitelen", "picture, writing"],
    ["sona", "knowledge, understand, wisdom"],
    ["soweli", "animal, land mammal, lovable animal"],
    ["suli", "big, tall, long, adult, important"],
    ["suno", "sun, light, star"],
    ["supa", "horizontal surface, table, chair, floor"],
    ["suwi", "candy, sweet, sweet food"],
    ["tan", "from, by, because of, since, origin, cause"],
    ["taso", "only, sole reason, sole purpose"],
    ["tawa", "towards, in the direction of, away, walk, movement, transport"],
    ["telo", "water, liquid, juice, sauce"],
    ["tenpo", "time, period of time, moment, duration"],
    ["tu", "two, duo, pair, separate, cut, divide"],
    ["toki", "language, speak, speech, talk, communication"],
    ["tomo", "indoor constructed space, house, home, rom, building"],
    ["unpa", "reproduction"],
    ["uta", "mouth, oral"],
    ["utala", "conflict, dispute, fight, competition, war, battle, attack"],
    ["walo", "white, light"],
    ["wan", "one, a unite, make one, whole"],
    ["waso", "bird, winged animal"],
    ["wawa", "energy, strength, power"],
    ["weka", "away, absent, missing, remove, get rid of, throw away"],
    ["wile", "want, need, wish, have to, must will, should, desire, like"]
]);

input.addEventListener("input", function() {
    output.textContent = words.get(input.value);
});